FROM sylecn/debian:stretch-slim-cn

#LABEL description="TODO add image description and uncomment this"

RUN set -x \
    && apt-get update -qq \
    && apt-get install -qq -y --no-install-recommends --no-install-suggests \
       DEPENDS \
    && rm -rf /var/lib/apt/lists/*

COPY DEB_PKG /
RUN ["dpkg", "-i", "DEB_PKG"]
CMD ["make", "run", "-C", "/opt/m3u8downloader"]
#EXPOSE 8082
